### PR TITLE
Explicitly use GNU Make

### PR DESCRIPTION
**Pull request by dveeden**
Checklist
---------
1. [CRUCIAL] Is the change for features that are already live in prod?
   * yes: ok

What
----

On many platforms `make` is GNU Make, but not on all. On FreeBSD it isn't. As the `Makefile` is GNU Make specific let's use `gmake` to allow this to work on more platforms.

References
----------

Issue: #1674

Test & Review
-------------

Manually, see issue

Open Questions / Follow-ups
---------------------------

### CODE REVIEW

**Review by brianstrauch — COMMENTED** [review]
Apologies for taking a while to review. I don't believe `gmake` comes pre-installed every system. Some of our users run the CLI on Windows machines, for example.

A possible multi-platform approach might be to create a variable called `$MAKE`, which is either set to `gmake` or `make`, depending on which one can be found in the user's `$PATH`.

**Comment by dveeden** [comment]
@brianstrauch Are you sure Windows has GNU Make as `make` but not as `gmake`?

**Comment by dveeden** [comment]
Actually, looks like this is the proper way to do this: https://www.gnu.org/software/make/manual/make.html#MAKE-Variable

**Comment by dveeden** [comment]
With this I can call `make` on Linux and `gmake` on FreeBSD and everything should be fine. Note that `make` on FreeBSD is `bmake` which doesn't have the extended GNU behaviour.

**Comment by dveeden** [comment]
@brianstrauch Could you check the output of the Jenkins job? I don't have permission to see the output.

**Comment by brianstrauch** [comment]
@dveeden Thanks, `$(MAKE)` looks like a great solution! One minor papercut before I merge this: Can you run `make generate-packaging-patch` so our debian packaging can be updated? Thanks again for the PR!

**Comment by dveeden** [comment]
@brianstrauch Yes, done in c09434291866162f38383b4656a76134bdeeb87a

**Review by brianstrauch — APPROVED** [review]

**Pull request merged**
