### PR TITLE
Fix `confluent local` test

### PR DESCRIPTION
**Pull request by sgagniere**
Release Notes
-------------

Breaking Changes
- PLACEHOLDER

New Features
- PLACEHOLDER

Bug Fixes
- PLACEHOLDER

Checklist
---------
- [x] Leave this box unchecked if features are not yet available in production

What
----
More kafka topic configs are being returned in `confluent local kafka topic describe`, so this PR updates the golden file to fix the test.

References
----------

Test & Review
-------------

### CODE REVIEW

**Review by brianstrauch — APPROVED** [review]
I don't remember this test failing in the past. What changed?

**Comment by sgagniere** [comment]
@brianstrauch A new version of the confluent-local image, I think. I now have two versions (one dangling) after running the local tests locally.

**Comment by brianstrauch** [comment]
The CLI should not be using the "latest" tag of that image, if that's what you mean. We should validate that each image works with our test suite before updating it.

**Comment by javabrett** [comment]
> The CLI should not be using the "latest" tag of that image, if that's what you mean. We should validate that each image works with our test suite before updating it.

However now we are pinned to a 2-versions-old version, since there's no release process to trigger review/test/bump-version for this.

**Pull request merged**
