### PR TITLE
[DGS-5681] Add ability to update network type for SR from CLI

### PR DESCRIPTION
**Pull request by karthikeyanas**
Release Notes
-------------
New Features
- Support for private link in Schema Registry

Checklist
---------
1. [CRUCIAL] Is the change for features that are already live in prod?
   * No

What
----
 Add ability to update network type for SR from CLI. This is required to for enabling private link access to SR cluster in ccloud. Network type can be specified with `--networkType` in `enable` and `update` schemaregistry commands. Accepted values for networkType are `private` or `public`

References
----------
https://confluentinc.atlassian.net/browse/DGS-5681

Test & Review
-------------
TDB

Open Questions / Follow-ups
---------------------------
None

### CODE REVIEW

**Comment by brianstrauch** [comment]
> [DO NOT REVIIEW]

Please mark as "Draft" to block merges!

**Comment by brianstrauch** [comment]
@karthikeyanas do you still plan to merge this?

**Comment by karthikeyanas** [comment]
> @karthikeyanas do you still plan to merge this?

We intend to merge this change when we the release of the Private Link for SR. Additionally, we are considering alterations in the approach to enabling Data Governance, which could potentially render this pull request unnecessary. If we determine that this CLI is not required in the new approach, I will close it

**Comment by karthikeyanas** [comment]
This is not required with always-on governance

**Pull request closed without merging**
