### PR TITLE
[RCCA-10621] Pass resource IDs to Kafka REST in `kafka acl` commands

### PR DESCRIPTION
**Pull request by brianstrauch**
Checklist
---------
1. [CRUCIAL] Is the change for features that are already live in prod?
   * yes: ok

What
----
Previously, all principals were being passed to Kafka REST as numeric IDs when creating/listing/deleting a Kafka ACL with `kafka acl`. These should no longer be converted prior to making the request because the backend can handle resource IDs now.

The backend may still respond with numeric IDs (if it can't make the mapping), so I'm keeping the code that maps numeric IDs back to resource IDs so we don't accidentally show numeric IDs to the user.

References
----------
https://confluentinc.atlassian.net/browse/RCCA-10621

Test & Review
-------------
Verified that Kafka ACLs can still be created, listed, and deleted.

### CODE REVIEW

**Review by sgagniere — APPROVED** [review]
👍

**Comment by MuweiHe** [comment]
`so I'm keeping the code that maps numeric IDs back to resource IDs so we don't accidentally show numeric IDs to the user.`
what happens if backend returns resource id? it's now showing that part of code in this pr maybe, so just curious

**Comment by brianstrauch** [comment]
> what happens if backend returns resource id?

@MuweiHe The backend returns resource IDs by default. It only returns numeric IDs if it can't perform the mapping (in that case, we identify that the principal doesn't exist, and we don't show it to the user)

**Comment by brianstrauch** [comment]
The Kafka team has not fully deployed this in production. Marking as draft until it's ready.

**Comment by brianstrauch** [comment]
A force push may have knocked this out-of-sync with the main branch. Closing and reopening this PR on a different branch.

**Pull request closed without merging**
